### ISSUE TITLE
API key and userid not being set from environment variables

### ISSUE THREAD

**Issue by jike212** [jilabaji/tookan#1]
I'm testing Tookan for use in a project however I'm having difficulty getting the API key and user ID to get passed to Tookan.

The key and userid are set properly in the `.env` file but the variable is not being set properly. I've attached a screenshot below showing the value of `process.env.tookan_key` and how the `tookan_key` const variable is not being set

![tookan-api](https://user-images.githubusercontent.com/28184313/50764940-5f47c480-1285-11e9-977e-bc8203c90b15.jpg)

**Comment by jike212** [comment]
Turns out the require statement for `dotenv` was loading later than expected. I've moved it up so that environment variables are loaded earlier and it is working appropriately now.

**Comment by jilabaji** [comment]
@jike212 sorry yaar! could not find time to follow up on the repo's! iam back will look into they repo's closely to fix bugs and features....
